{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3346ac23",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-14 19:51:43.132 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager\n",
      "2025-11-14 19:51:43.149 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.149 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.208 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/anaconda3/lib/python3.13/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-14 19:51:43.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.209 No runtime found, using MemoryCacheStorageManager\n",
      "2025-11-14 19:51:43.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.209 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.438 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-14 19:51:43.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-14 19:51:43.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "\n",
    "EXCEL_FILE = \"gre_words.xlsx\"  # 같은 폴더에 있는 엑셀 파일 이름\n",
    "\n",
    "\n",
    "# ===== 데이터 불러오기 =====\n",
    "@st.cache_data\n",
    "def load_words(file_path):\n",
    "    df = pd.read_excel(file_path)\n",
    "    df = df.iloc[:, :2].dropna()   # 앞의 두 컬럼만 사용 (단어, 뜻)\n",
    "    df.columns = [\"word\", \"meaning\"]\n",
    "    return df.reset_index(drop=True)\n",
    "\n",
    "\n",
    "def is_correct(user_answer: str, correct_meaning: str) -> bool:\n",
    "    \"\"\"사용자 답이 정답 의미와 '대충' 일치하는지 확인 (공백/대소문자 무시).\"\"\"\n",
    "    def norm(s):\n",
    "        return \"\".join(str(s).lower().split())\n",
    "\n",
    "    ua = norm(user_answer)\n",
    "    cm = norm(correct_meaning)\n",
    "\n",
    "    if not ua:\n",
    "        return False\n",
    "\n",
    "    # 사용자가 쓴 답이 정답에 포함되거나, 정답이 사용자의 답에 포함되면 정답 처리\n",
    "    return ua in cm or cm in ua\n",
    "\n",
    "\n",
    "# ===== 세션 초기화 함수 =====\n",
    "def init_quiz_state(df, n_questions: int):\n",
    "    st.session_state.quiz_df = df.sample(n_questions).reset_index(drop=True)\n",
    "    st.session_state.current_idx = 0\n",
    "    st.session_state.score = 0\n",
    "    st.session_state.finished = False\n",
    "    st.session_state.last_feedback = None  # (correct(bool), correct_meaning(str))\n",
    "\n",
    "\n",
    "# ===== 메인 앱 =====\n",
    "def main():\n",
    "    st.set_page_config(page_title=\"GRE 단어 퀴즈\", page_icon=\"📚\", layout=\"centered\")\n",
    "\n",
    "    st.title(\"📚 GRE 단어 퀴즈\")\n",
    "    st.caption(\"엑셀에 저장된 단어를 기반으로 랜덤 퀴즈를 풀어보세요!\")\n",
    "\n",
    "    # 엑셀 로딩\n",
    "    try:\n",
    "        df = load_words(EXCEL_FILE)\n",
    "    except FileNotFoundError:\n",
    "        st.error(f\"엑셀 파일 `{EXCEL_FILE}` 을(를) 찾을 수 없습니다. \"\n",
    "                 \"동일한 폴더에 파일을 저장했는지 확인해주세요.\")\n",
    "        return\n",
    "    except Exception as e:\n",
    "        st.error(f\"엑셀 파일을 읽는 중 오류가 발생했습니다: {e}\")\n",
    "        return\n",
    "\n",
    "    st.success(f\"현재 {len(df)}개의 단어를 불러왔어요.\")\n",
    "\n",
    "    # 왼쪽은 설정, 오른쪽은 설명\n",
    "    col1, col2 = st.columns([2, 1])\n",
    "\n",
    "    with col1:\n",
    "        n_default = 30 if len(df) >= 30 else len(df)\n",
    "        n_questions = st.number_input(\n",
    "            \"한 세트에 풀 문제 개수\",\n",
    "            min_value=1,\n",
    "            max_value=len(df),\n",
    "            value=n_default,\n",
    "            step=1,\n",
    "            help=\"랜덤으로 이 개수만큼 뽑아서 문제를 만들어요.\",\n",
    "        )\n",
    "\n",
    "        if st.button(\"🎯 퀴즈 시작하기\", type=\"primary\"):\n",
    "            init_quiz_state(df, n_questions)\n",
    "            st.experimental_rerun()\n",
    "\n",
    "    with col2:\n",
    "        st.markdown(\n",
    "            \"\"\"\n",
    "            **사용 방법**\n",
    "            1. `gre_words.xlsx` 파일을 같은 폴더에 둡니다.  \n",
    "            2. 풀고 싶은 문제 개수를 정하고 **퀴즈 시작하기**를 누릅니다.  \n",
    "            3. 단어의 뜻을 입력하고 제출하면 정답 여부가 뜹니다.  \n",
    "            4. 한 세트가 끝나면 점수가 요약됩니다.\n",
    "            \"\"\"\n",
    "        )\n",
    "\n",
    "    # 아직 퀴즈 시작 전이면 여기서 끝\n",
    "    if \"quiz_df\" not in st.session_state or st.session_state.finished:\n",
    "        st.markdown(\"---\")\n",
    "        st.info(\"위에서 **문항 수를 정한 뒤 퀴즈를 시작**해주세요.\")\n",
    "        return\n",
    "\n",
    "    quiz_df = st.session_state.quiz_df\n",
    "    idx = st.session_state.current_idx\n",
    "    total = len(quiz_df)\n",
    "\n",
    "    st.markdown(\"---\")\n",
    "\n",
    "    # 방금 전 문제 피드백\n",
    "    if st.session_state.last_feedback is not None:\n",
    "        correct, correct_meaning = st.session_state.last_feedback\n",
    "        if correct:\n",
    "            st.success(\"✅ 방금 문제: 정답!\")\n",
    "        else:\n",
    "            st.error(f\"❌ 방금 문제: 오답입니다. 정답: `{correct_meaning}`\")\n",
    "\n",
    "    # 모든 문제를 다 풀었으면 결과만 보여주기\n",
    "    if idx >= total:\n",
    "        st.session_state.finished = True\n",
    "        score = st.session_state.score\n",
    "        st.markdown(\"## 🎉 세트 종료!\")\n",
    "        st.write(f\"**점수: {score} / {total}**  (정답률 {score/total*100:.1f}%)\")\n",
    "\n",
    "        if score / total >= 0.8:\n",
    "            st.success(\"좋아요! 이 세트는 꽤 익숙해진 것 같아요 😎\")\n",
    "        elif score / total >= 0.5:\n",
    "            st.info(\"절반 이상 맞췄어요. 한 번 더 돌리면 더 익숙해질 거예요 💪\")\n",
    "        else:\n",
    "            st.warning(\"조금 어려웠죠? 틀린 문제 위주로 다시 보는 걸 추천해요 📖\")\n",
    "\n",
    "        if st.button(\"🔁 새로운 세트로 다시 풀기\"):\n",
    "            init_quiz_state(df, total)\n",
    "            st.experimental_rerun()\n",
    "        return\n",
    "\n",
    "    # ===== 현재 문제 표시 =====\n",
    "    row = quiz_df.iloc[idx]\n",
    "    word = row[\"word\"]\n",
    "    meaning = row[\"meaning\"]\n",
    "\n",
    "    st.subheader(f\"문제 {idx + 1} / {total}\")\n",
    "    st.markdown(f\"### ✅ 단어: **{word}**\")\n",
    "\n",
    "    with st.form(key=f\"quiz_form_{idx}\"):\n",
    "        user_answer = st.text_input(\"이 단어의 뜻을 적어보세요\", key=f\"answer_{idx}\")\n",
    "        submitted = st.form_submit_button(\"제출\")\n",
    "\n",
    "    if submitted:\n",
    "        correct = is_correct(user_answer, meaning)\n",
    "        if correct:\n",
    "            st.session_state.score += 1\n",
    "\n",
    "        # 방금 문제에 대한 피드백 저장\n",
    "        st.session_state.last_feedback = (correct, meaning)\n",
    "        # 다음 문제로 이동\n",
    "        st.session_state.current_idx += 1\n",
    "        st.experimental_rerun()\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "71ab6015",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
